matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode9.4

language: node_js
node_js:
  - "12.4.0"
sudo: required

cache:
  directories:
    - node_modules

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - npm install
  - npm install -g codecov
  - npm run build

script:
  - npm run lint
  - npm test

after_success:
  - codecov
