version: 1.0.0.{build}
configuration:
- Debug
- Release
platform:
- x64
- x86
- Any CPU
before_build:
- ps: cmake . -DEXAMPLES=Yes
build:
  project: ALL_BUILD.vcxproj
  verbosity: normal
test_script:
- cmd: test\%CONFIGURATION%\inform_unittest.exe
artifacts:
- path: 'Release\inform.dll'
  name: dll
- path: 'Release\inform.lib'
  name: lib
- path: 'Release\inform_static.lib'
  name: static
